SELECT
    exp.person_id,
    exp.title,
    edu.program,
    CASE
        WHEN edu.program LIKE '%computer%'
        OR edu.program LIKE '%software%'
        OR edu.program LIKE '%cyber%'
        OR edu.program LIKE '%computing%'
        OR edu.program LIKE '%programming%'
        OR edu.program LIKE '%information system%'
        OR edu.program LIKE '%information technology%' THEN 'Computer Science and IT'
        WHEN edu.program LIKE '%law%'
        OR edu.program LIKE '%legal%'
        OR edu.program LIKE '%justice%'
        OR edu.program LIKE '%crimin%'
        OR edu.program LIKE '%jurisprudence%' THEN 'Law'
        WHEN edu.program LIKE '%business%'
        OR edu.program LIKE '%accounting%'
        OR edu.program LIKE '%finan%'
        OR edu.program LIKE '%market%'
        OR edu.program LIKE '%commerce%'
        OR edu.program LIKE '%econ%' THEN 'Business / Economics / Marketing'
        WHEN edu.program LIKE '%data%' THEN 'Data and Databases'
        WHEN edu.program LIKE '%math%'
        OR edu.program LIKE '%physics%' THEN 'Math and Physics'
        WHEN edu.program LIKE '%religio%'
        OR edu.program LIKE '%theol%'
        OR edu.program LIKE '%psychology%'
        OR edu.program LIKE '%cognitive%'
        OR edu.program LIKE '%philosoph%' THEN 'Psychology and Religion'
        WHEN edu.program LIKE '%health%'
        OR edu.program LIKE '%medic%'
        OR edu.program LIKE '%dentist%'
        OR edu.program LIKE '%nurs%'
        OR edu.program LIKE '%plant%'
        OR edu.program LIKE '%animal%'
        OR edu.program LIKE '%bio%' THEN 'Biology, Bioengineering and Health'
        WHEN edu.program LIKE '%electr%' THEN 'Electrical'
        WHEN edu.program LIKE '%journalism%'
        OR edu.program LIKE '%english%'
        OR edu.program LIKE '%political%'
        OR edu.program LIKE '%literature%' THEN 'Political Science, Journalism and Literature'
        WHEN edu.program LIKE '%art%'
        OR edu.program LIKE '%music%'
        OR edu.program LIKE '%photograph%'
        OR edu.program LIKE '%film%' THEN 'Art, music and film'
        WHEN edu.program LIKE '%high school%'
        OR edu.program LIKE '%course%'
        OR edu.program LIKE '%certificat%' THEN 'High school, certificate or course'
        WHEN edu.program LIKE '%engineering%' THEN 'Other Engineering'
        WHEN edu.program IS NULL
        OR edu.program = 'Unknown' THEN 'Unknown'
        ELSE 'Other'
    END AS 'degree'
FROM
    experience_table_clean AS exp
    JOIN education_table_clean AS edu ON exp.person_id = edu.person_id
WHERE
    exp.title LIKE '%developer'
    OR exp.title LIKE '%software%'
    OR exp.title LIKE '%programmer%'
    OR exp.title LIKE '%devops%'
    OR exp.title LIKE '%data engineer%'
    OR exp.title LIKE '%data scien%'
    OR exp.title LIKE '%data anal%'
    OR exp.title LIKE '%cloud%'
    OR exp.title LIKE '%cyber%'
    OR exp.title LIKE '%web%'
    OR exp.title LIKE '%system admin%'
    OR exp.title LIKE '%machine learn%'
    OR exp.title LIKE '%artificial int%'